### ISSUE TITLE
Functions not recognizing API Credentials in Renvir file.

### ISSUE THREAD

**Issue by ThomasPepperz** [hfshr/bitmexr#1]
Greetings, 

I am having difficulty working functions that require a API credentials. I edited my R environment file as instructed yet I keep receiving the following error:

```
Error: The API returned an error:  Authorization Required
```

**Comment by hfshr** [comment]
Hi,

Have you restarted your R session after editing the .Renviron file? A restart is needed after making changes to the .Renviron file for it to be read in properly by the functions (this is missing from the docs so apologies!).

 If if still doesn't work after restarting let me know!

**Comment by ThomasPepperz** [comment]
Thank you for responding. I did just recently try to restart after making the changes. This is what is in my Renvir file:

```
testnet_bitmex_apikey = "PfDX*****t"
testnet_bitmex_apisecret = "mqfVZ********"
```

Where each string is my test net key. 

One thing I was wondering about is why some of my API Key var names are yellow and all caps but this one isn't? I'm not sure if double vs. single quotations matter et cetera. 

Some of the functions I tried to use are

```
get_bitmex("/apiKey")
tn_get_bitmex("/user/wallet")
```

Also tried different combos of using 'tn' before certain functions. 

I used this to open up my file:

 ```usethis::edit_r_environ()
```

And tried to edit my environ file manually. 

I also tried 

```
Sys.setenv(TESTNET_BITMEX_APIKEY = "PfDX*******")
Sys.setenv(TESTNET_BITMEX_APISECRET = "mqfV********7")
```

Note the all caps. I'm at a lost really.

**Comment by hfshr** [comment]
Thanks for the update, 

Your first example looks exactly right. If you remove the space around the "=" var names should change colour, but I don't think that or being capitalised/double vs single quotes should matter.

After creating the .Renviron file (see [Authentication Vignette](https://hfshr.github.io/bitmexr/articles/authentication.html)) and restarting R you can then check if the following works:

```
Sys.getenv("testnet_bitmex_apikey")
```
That should print the API key you've just put in the .Renviron (Can also test the secret by using `Sys.getenv("testnet_bitmex_apisecret")`)

As you're using a testnet API key/secret, you can only use the "tn_*" functions that need authentication. In addition, some of the generic functions like `tn_get_bitmex()` need `use_auth = TRUE` to indicate you want to use authentication with your request (see `?tn_get_bitmex()`)

So adding this to your example:
```
tn_get_bitmex("/user/wallet", use_auth = TRUE)
```
should work.

This may also be really obvious (apologies if so!) and I'm only including because I made this mistake at one point (doh!)... but you can't use an API key/secret from a live account to access the testnet. An API key/ secret created from a testnet account on www.testnet.bitmex.com is needed  for the "tn_*" functions to work.

Hope that helps, let me know if not!
